server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/usersDB
    username: usersAdmin
    password: admin1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: users-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
